### ISSUE TITLE
Running the contributed command: 'vscode-extension-profiles.Create' failed

### ISSUE THREAD

**Issue by hamolicious** [evald24/vscode-extensions-profiles#10]
When creating a profile, the `Create` command returns an error.
[Link to video showing the error](https://www.youtube.com/watch?v=p38ra-K6riw)

After some playing around, here is the breakdown of all non-functioning commands:
- `Create` : `Running the contributed command: 'vscode-extension-profiles.Create' failed` but only after specifying a name
- `Refresh` : `Running the contributed command: 'vscode-extension-profiles.Refresh' failed`

Other commands seem to work fine (considering that there are no profiles as I cannot create them).

I have tried multiple different workspaces and no workspace with no luck.

**Comment by evald24** [comment]
Thanks for the video demo of the error.

What vscode version and operating system version are you using and is nodejs installed?

**Comment by hamolicious** [comment]
Running Windows 10
VSCode Version 1.57.1
NodeJS 14.16.0 is installed and working as I was writing a similar extension before I came across yours.

**Comment by evald24** [comment]
Okay. I will install Windows 10 on a virtual machine and the versions you specified and try to find the cause of the error.

**Comment by hamolicious** [comment]
I did some testing of my own and it seems that VSCode isn't generating a `.obsolete` file that you are trying to read:
![error_screenshot](https://i.ibb.co/rvLhWrK/Screenshot-2021-07-05-104622.png)
This error is thrown upon load and the commands mentioned above

**Comment by evald24** [comment]
Thank you, now then I will quickly try to fix it.

**Comment by evald24** [comment]
I have released an update fixing this bug.

The ".obsolete" contains a list of extensions to be ignored. This is necessary because the folder with extensions may contain outdated versions of the same extensions.

For example:
![image](https://user-images.githubusercontent.com/10986227/124455518-8080c180-ddab-11eb-9312-e39719ecb055.png)

**Comment by hamolicious** [comment]
Thanks so much for a fast fix, I have updated and will use the extension for a couple weeks and see if any issues arise... other than that, AMAZING extension and thanks again.
