### ISSUE TITLE
Running the contributed command: 'vscode-extension-profiles.Apply' failed.

### ISSUE THREAD

**Issue by 8NAF** [evald24/vscode-extensions-profiles#14]
OS: Window 10
VS Code Version: 1.60.0

The `Select and apply profile` command doesn't work.

![Bug](https://user-images.githubusercontent.com/62730599/132160639-5944b03f-8ef7-4aa3-82aa-116f99286758.gif)

I tried many different workspaces and no workspace, but it still doesn't work.

**Comment by evald24** [comment]
Thanks for pointing out the error. I am very busy right now and cannot tackle this problem. I will be working on bug fixes and improvements shortly.

**Comment by da-the-dev** [comment]
Maybe the same as #16? Would be really handy to see an error log.

**Comment by evald24** [comment]
@8NAF I am very sorry that I could not fix the bug earlier, I was very busy. If it is still relevant, please check if the error has fixed

**Comment by 8NAF** [comment]
@evald24, Everything works fine on my Window and Ubuntu 👍. But I have a new issue 😅,  I will close this and create a new issue.
