### ISSUE TITLE
Error, does not work on Apple M1

### ISSUE THREAD

**Issue by evald24** [evald24/vscode-extensions-profiles#21]
```
Activating extension 'evald24.vscode-extension-profiles' failed: Cannot find module '/Users/esmalyakov/.vscode/extensions/evald24.vscode-extension-profiles-1.1.1/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node'
```

**Comment by da-the-dev** [comment]
npm's SQLite uses precompiled binaries and these binaries seem to be missing. You just have to install them and that's it.

**Comment by da-the-dev** [comment]
> npm's SQLite uses precompiled binaries and these binaries seem to be missing. You just have to install them and that's it.

For now, you literally can go into this extension's folder (different on each system, but something like `root_folder/.vscode/extensions/evald24.vscode-extensions-profiles-{version}`) and run `npm i`. It's going to update the libraries and get the correct binaries for your system. 

For @evald24: You can then just copy the `napi-v3-darwin-arm64` folder to `node_modules/sqlite3/lib/binding` in your project folder and publish the extension to fix it. There's gotta be a way of installing all available binaries so there won't be any inconsistencies, but idk how to do it.

**Comment by evald24** [comment]
Thank you, I was at work and left this question for myself. Today I will decide =)
