### ISSUE TITLE
Default Profile when starting VSCode

### ISSUE THREAD

**Issue by mbeps** [evald24/vscode-extensions-profiles#23]
It would be nice to have a default profile every time VSCode is opened. Currently, the last profile used it opened. This would be useful if someone has a lot of extensions (such as language support for many languages) but only needs limited functionalities such as GitLens and Git Tree, loading everything will be too slow and heavy on resources

**Comment by evald24** [comment]
Disable all extensions by default

<img width="592" alt="image" src="https://user-images.githubusercontent.com/10986227/174473860-09de27c2-99ab-4bed-b249-d555a9db7f01.png">

And include only the necessary extensions
