### ISSUE TITLE
Applying profile does not enable extensions

### ISSUE THREAD

**Issue by andrewcrook** [evald24/vscode-extensions-profiles#27]
When I disable all extensions except the profile extension which I have made global  
then apply a profile it doesn’t enable the extensions in the profile.
Was this meant to be apart of the features? 
If not, I think it needs adding or at least have an option.

macOS 12.2.1
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

**Comment by evald24** [comment]
I apologize for not answering for so long, there was a lot to do. The profile has long added support for a global profile to which you can add the necessary extensions and they will be applied together with the selected one.

To do this, run the "Edit profile" command and select "--- Global Profile ---", specify the necessary extensions there

<img width="617" alt="image" src="https://user-images.githubusercontent.com/10986227/174474000-bb4b6d7d-69fb-4d37-990b-c116bf850a95.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/10986227/174474025-2636e774-b5ad-463f-ac7d-d0c6e6fb6e49.png">
