### ISSUE TITLE
Applying a profile does not take effect until VS Code is restarted

### ISSUE THREAD

**Issue by no-stack-dub-sack** [evald24/vscode-extensions-profiles#34]
Hi - when I apply a profile, the enabled/disabled extensions don't actually change until I restart VS Code. Is this the intended behavior?

I've also tried using `Developer: Reload Window` after applying a profile and that does not work either. No matter what I do, it seems like the changes don't take effect until I restart the program. This is already an improvement over having no profiles, but it would be great to get this behavior without a restart.

I'm on Windows.

Thanks!

**Comment by evald24** [comment]
@no-stack-dub-sack Hi! This behavior appeared due to VSCode changes a few weeks earlier. I am now trying to figure out the possibility of how to restore the correct operation of the extension
https://github.com/microsoft/vscode/issues/151985#issuecomment-1154699511

**Comment by evald24** [comment]
Added a warning that you need to restart "VSCode"

> With the recent update of VSCode, the process of restarting extensions based on the workspace has changed and now requires a full restart of VSCode. Now I'm thinking about how it would be possible to apply the profile without a full reboot, if you know or have suggestions on how to improve the behavior of the extension, please create an issue


If I find a solution that will avoid this, I will definitely release an extension update.
